// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: asset.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (id, user_id, name, type, current_value, purchased_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, type, current_value, purchased_at, created_at, updated_at
`

type CreateAssetParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	Type         string
	CurrentValue int64
	PurchasedAt  time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, createAsset,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.CurrentValue,
		arg.PurchasedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CurrentValue,
		&i.PurchasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssetsByUserID = `-- name: GetAssetsByUserID :many
SELECT id, user_id, name, type, current_value, purchased_at, created_at, updated_at FROM assets WHERE user_id = $1 LIMIT $2 OFFSET $3
`

type GetAssetsByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetAssetsByUserID(ctx context.Context, arg GetAssetsByUserIDParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, getAssetsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.CurrentValue,
			&i.PurchasedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
